version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint-tests.sh
    container_name: mongodb-crud-to-do-list
    volumes:
      - .:/home/node/app
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=test

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    