version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: mongodb-crud-to-do-list
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  # dbtest:
  #   image: mongo:latest
  #   container_name: dbtest
  #   restart: always
  #   ports:
  #     - 27017:27017
      
volumes:
  mongodb_data_container: